import { zodResolver } from '@hookform/resolvers/zod';
import { addDays, addMonths, eachDayOfInterval, endOfMonth, format, isPast, isSameDay, isToday, startOfMonth, subMonths } from 'date-fns';
import { AlertCircle, AlignLeft, Calendar, ChevronLeft, ChevronRight, Clock, HelpCircle, LayoutGrid, Zap, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Controller, useForm } from 'react-hook-form';
import { useNavigate } from 'react-router-dom';
import { z } from 'zod';
import { marketsApi } from '../api/markets';
import { CustomSelect } from '../components/common/CustomSelect';
import { TxSuccessModal } from '../components/common/TxSuccessModal';
import { useContract } from '../hooks/useContract';

const createMarketSchema = z.object({
  question: z.string().min(10, 'Question must be at least 10 characters').max(500),
  description: z.string().max(2000).optional(),
  category: z.string().min(1, 'Category is required'),
  tags: z.array(z.string()).default([]),
  resolutionDate: z.string().refine(val => new Date(val) > new Date(), {
    message: 'Resolution date must be in the future',
  }),
});

type CreateMarketFormData = z.infer<typeof createMarketSchema>;

export function CreateMarket() {
  const navigate = useNavigate();
  const { createMarket, isInitializing } = useContract();
  const [successData, setSuccessData] = useState<{ txHash: string; slug: string; question: string } | null>(null);
  
  const {
    register,
    handleSubmit,
    control,
    setValue,
    watch,
    formState: { errors, isSubmitting },
  } = useForm<CreateMarketFormData>({
    resolver: zodResolver(createMarketSchema),
    defaultValues: {
      category: 'Politics',
      tags: [],
    },
  });

  const [tagInput, setTagInput] = useState('');
  const tags = watch('tags') || [];

  // Resolution Timeline States (Moved to top-level for Rules of Hooks)
  const resolutionDate = watch('resolutionDate');
  const initialDate = resolutionDate ? new Date(resolutionDate) : addDays(new Date(), 1);
  const [currentMonth, setCurrentMonth] = useState(startOfMonth(initialDate));
  const [selectedTime, setSelectedTime] = useState(format(initialDate, 'HH:mm'));

  const days = useMemo(() => {
    return eachDayOfInterval({
      start: startOfMonth(currentMonth),
      end: endOfMonth(currentMonth),
    });
  }, [currentMonth]);

  const addTag = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      e.preventDefault();
      const newTag = tagInput.trim();
      if (newTag && !tags.includes(newTag)) {
        setValue('tags', [...tags, newTag]);
        setTagInput('');
      }
    }
  };

  const removeTag = (tagToRemove: string) => {
    setValue('tags', tags.filter(t => t !== tagToRemove));
  };

  const onSubmit = async (data: CreateMarketFormData) => {
    console.log('DEBUG: CreateMarket.onSubmit called with form data:', data);
    try {
      // Step 1: Create on-chain
      console.log('DEBUG: Initiating on-chain market creation via hook...');
      const result = await createMarket(
        '', // marketId auto-generated by contract
        data.question,
        new Date(data.resolutionDate)
      );

      console.log('DEBUG: on-chain market creation finished. result:', result);

      if (result) {
        const { txHash, onchainId } = result;
        // Step 2: Sync to backend (done in background or wait)
        console.log(`DEBUG: Synchronizing new market (ID: ${onchainId}) to backend database...`);
        try {
          const market = await marketsApi.create({
            question: data.question,
            description: data.description,
            category: data.category,
            tags: data.tags,
            endTime: new Date(data.resolutionDate).toISOString(),
            resolutionSource: 'Oracle',
            onchainId, 
            txHash,
          });
          
          console.log('DEBUG: Backend synchronization successful. slug:', market.slug);
          
          // Show CUSTOM SUCCESS MODAL instead of redirecting
          setSuccessData({
            txHash,
            slug: market.slug || market.id,
            question: data.question
          });
          
        } catch (syncError) {
          console.error('DEBUG: Backend synchronization failed:', syncError);
          // If backend fails but on-chain succeeds, we still show the hash
          setSuccessData({
            txHash,
            slug: '', // Can't redirect to detail if sync failed
            question: data.question
          });
        }
      }
    } catch (error: any) {
      console.error('DEBUG: CreateMarket.onSubmit caught top-level error:', error);
      // Toast handled by contract service
    }
  };

  return (
    <div className="max-w-4xl mx-auto py-12 px-6">
      <div className="mb-12 space-y-4">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-electric-blue/10 rounded-sm">
            <LayoutGrid className="w-5 h-5 text-electric-blue" />
          </div>
          <h1 className="text-4xl font-bold text-white tracking-tight">Create Market</h1>
        </div>
      </div>

      <form onSubmit={handleSubmit(onSubmit)} className="space-y-8 bg-slate-900/40 border border-white/5 p-8 rounded-sm backdrop-blur-sm">
        <div className="space-y-6">
          {/* Question Input */}
          <div className="space-y-2">
            <label className="text-[10px] font-mono text-slate-500 uppercase tracking-widest flex items-center justify-between">
              <span className="flex items-center gap-2">
                <HelpCircle className="w-3.5 h-3.5 text-electric-blue" />
                Market Question
              </span>
              {errors.question && (
                <span className="text-red-400 flex items-center gap-1">
                  <AlertCircle className="w-3 h-3" /> {errors.question.message}
                </span>
              )}
            </label>
            <input
              {...register('question')}
              type="text"
              placeholder="e.g. Will Midnight mainnet launch in 2025?"
              className={`w-full bg-slate-950 border rounded-sm px-4 py-3 text-white placeholder:text-slate-700 focus:outline-none transition-all font-light ${
                errors.question ? 'border-red-500/50' : 'border-white/10 focus:border-electric-blue/50'
              }`}
            />
          </div>
          
          {/* Description Input */}
          <div className="space-y-2">
            <label className="text-[10px] font-mono text-slate-500 uppercase tracking-widest flex items-center justify-between">
              <span className="flex items-center gap-2">
                <AlignLeft className="w-3.5 h-3.5 text-electric-blue" />
                Additional Details (Optional)
              </span>
            </label>
            <textarea
              {...register('description')}
              rows={3}
              placeholder="Provide context or resolution criteria..."
              className="w-full bg-slate-950 border border-white/10 rounded-sm px-4 py-3 text-white placeholder:text-slate-700 focus:outline-none focus:border-electric-blue/50 transition-all font-light resize-none text-sm"
            />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {/* Category Selection */}
            <CustomSelect
              label="Market Category"
              value={watch('category')}
              onChange={(val) => setValue('category', val)}
              error={errors.category?.message}
              options={[
                { label: 'POLITICS', value: 'Politics', description: 'Elections, government, and policy' },
                { label: 'SPORTS', value: 'Sports', description: 'Professional leagues and major events' },
                { label: 'CRYPTO', value: 'Crypto', description: 'Currencies, protocols, and digital assets' },
                { label: 'FINANCE', value: 'Finance', description: 'Markets, stocks, and economic indicators' },
                { label: 'GEOPOLITICS', value: 'Geopolitics', description: 'International relations and security' },
                { label: 'TECH', value: 'Tech', description: 'Innovation, AI, and consumer tech' },
                { label: 'CULTURE', value: 'Culture', description: 'Entertainment, art, and society' },
                { label: 'ECONOMY', value: 'Economy', description: 'Macro trends and fiscal data' },
                { label: 'WEATHER', value: 'Weather', description: 'Climate events and environmental data' },
                { label: 'ELECTIONS', value: 'Elections', description: 'Voting, polls, and political contests' },
                { label: 'OTHERS', value: 'Others', description: 'Anything else' },
              ]}
            />

            {/* Tags Input */}
            <div className="space-y-4">
              <label className="text-[10px] font-mono text-slate-500 uppercase tracking-widest flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <Zap className="w-3.5 h-3.5 text-electric-blue" />
                  Tags (Optional)
                </span>
              </label>
              <div className="space-y-3">
                <input
                  type="text"
                  value={tagInput}
                  onChange={(e) => setTagInput(e.target.value)}
                  onKeyDown={addTag}
                  placeholder="Type tag and press Enter..."
                  className="w-full bg-slate-950 border border-white/10 rounded-sm px-4 py-3 text-white placeholder:text-slate-700 focus:outline-none focus:border-electric-blue/50 transition-all font-light text-sm"
                />
                
                {/* Tag Pills */}
                <div className="flex flex-wrap gap-2">
                  {tags.map((tag) => (
                    <span 
                      key={tag} 
                      className="inline-flex items-center gap-2 px-3 py-1 bg-electric-blue/10 border border-electric-blue/20 rounded-sm text-[10px] font-mono text-electric-blue group"
                    >
                      {tag}
                      <button
                        type="button"
                        onClick={() => removeTag(tag)}
                        className="hover:text-white transition-colors"
                      >
                        <X className="w-3 h-3" />
                      </button>
                    </span>
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* Resolution Configuration */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {/* Custom Date/Time Selection */}
            <div className="space-y-4 md:col-span-2 border-t border-white/5 pt-8">
              <label className="text-[10px] font-mono text-slate-500 uppercase tracking-widest flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <Calendar className="w-3.5 h-3.5 text-electric-blue" />
                  Resolution Timeline
                </span>
                {errors.resolutionDate && (
                  <span className="text-red-400 flex items-center gap-1">
                    <AlertCircle className="w-3 h-3" /> Required
                  </span>
                )}
              </label>

              <Controller
                name="resolutionDate"
                control={control}
                render={({ field }) => {
                  const selectedDate = field.value ? new Date(field.value) : addDays(new Date(), 1);

                  const handleDateChange = (date: Date) => {
                    const [hours, minutes] = selectedTime.split(':').map(Number);
                    const newDate = new Date(date);
                    newDate.setHours(hours, minutes);
                    field.onChange(newDate.toISOString());
                  };

                  const handleTimeChange = (time: string) => {
                    setSelectedTime(time);
                    const [hours, minutes] = time.split(':').map(Number);
                    const newDate = new Date(selectedDate);
                    newDate.setHours(hours, minutes);
                    field.onChange(newDate.toISOString());
                  };

                  return (
                    <div className="flex flex-col md:flex-row gap-12 items-start bg-slate-950/50 p-6 border border-white/5 rounded-sm">
                      {/* Calendar Section */}
                      <div className="flex-1 space-y-4 w-full">
                        {/* Calendar Header */}
                        <div className="flex items-center justify-between px-2 mb-2">
                          <span className="text-sm font-bold text-white uppercase tracking-widest font-mono">
                            {format(currentMonth, 'MMMM yyyy')}
                          </span>
                          <div className="flex gap-2">
                            <button
                              type="button"
                              onClick={() => setCurrentMonth(subMonths(currentMonth, 1))}
                              className="p-2 hover:bg-white/10 rounded-sm transition-colors border border-white/5"
                            >
                              <ChevronLeft className="w-5 h-5 text-slate-400 hover:text-white" />
                            </button>
                            <button
                              type="button"
                              onClick={() => setCurrentMonth(addMonths(currentMonth, 1))}
                              className="p-2 hover:bg-white/10 rounded-sm transition-colors border border-white/5"
                            >
                              <ChevronRight className="w-5 h-5 text-slate-400 hover:text-white" />
                            </button>
                          </div>
                        </div>

                        {/* Day Grid */}
                        <div className="grid grid-cols-7 gap-2">
                          {['S', 'M', 'T', 'W', 'T', 'F', 'S'].map((day, index) => (
                            <div key={`${day}-${index}`} className="text-[10px] font-mono text-slate-600 text-center py-2 uppercase font-bold tracking-widest">
                              {day}
                            </div>
                          ))}
                          {days.map(day => {
                            const isSelected = isSameDay(day, selectedDate);
                            const isDisabled = isPast(day) && !isToday(day);
                            return (
                              <button
                                key={day.toISOString()}
                                type="button"
                                disabled={isDisabled}
                                onClick={() => handleDateChange(day)}
                                className={`aspect-square flex items-center justify-center text-xs rounded-sm transition-all font-mono relative ${
                                  isSelected
                                    ? 'bg-electric-blue text-white font-bold shadow-[0_0_20px_rgba(59,130,246,0.3)] z-10'
                                    : isDisabled
                                    ? 'text-slate-800 opacity-10 cursor-not-allowed'
                                    : 'text-slate-400 hover:bg-white/10 hover:text-white border border-transparent hover:border-white/10'
                                }`}
                              >
                                {format(day, 'd')}
                                {isToday(day) && !isSelected && (
                                  <div className="absolute bottom-1 w-1 h-1 bg-electric-blue rounded-full" />
                                )}
                              </button>
                            );
                          })}
                        </div>
                      </div>

                      {/* Divider */}
                      <div className="hidden md:block w-px h-64 bg-white/5 self-center" />

                      {/* Time Selection Section */}
                      <div className="w-full md:w-48 space-y-6 flex flex-col justify-center">
                        <div className="flex items-center gap-3 text-slate-400">
                          <Clock className="w-4 h-4 text-electric-blue" />
                          <span className="text-[11px] font-mono uppercase tracking-[0.2em] font-bold">Time</span>
                        </div>
                        <div className="space-y-4">
                          <div className="relative">
                            <input
                              type="time"
                              value={selectedTime}
                              onChange={(e) => handleTimeChange(e.target.value)}
                              className="w-full bg-slate-950 border border-white/10 rounded-sm px-4 py-4 text-xl text-white font-mono focus:outline-none focus:border-electric-blue/50 transition-all text-center tracking-widest"
                            />
                            <div className="absolute inset-y-0 right-4 flex items-center pointer-events-none opacity-20">
                              <Clock className="w-5 h-5" />
                            </div>
                          </div>
                          <div className="bg-electric-blue/5 p-4 rounded-sm border border-electric-blue/10">
                            <p className="text-[10px] text-slate-400 font-mono leading-tight uppercase text-center">
                              Set resolution time in UTC
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  );
                }}
              />
            </div>

            <div className="space-y-8">
            <div className="space-y-4">
              {/* Optional: Add other settings here if needed */}
            </div>
            </div>
          </div>
        </div>

        <div className="pt-6 border-t border-white/5">
          <button
            type="submit"
            disabled={isSubmitting || isInitializing}
            className="w-full py-4 bg-electric-blue text-white rounded-sm font-bold text-[11px] tracking-[0.2em] uppercase hover:brightness-110 disabled:opacity-50 transition-all flex items-center justify-center gap-3 shadow-[0_0_30px_rgba(59,130,246,0.3)]"
          >
            {isSubmitting ? (
              <div className="w-4 h-4 border-2 border-white/20 border-t-white rounded-full animate-spin" />
            ) : (
              <Zap className="w-4 h-4" />
            )}
            Launch Market
          </button>
        </div>
      </form>

      <div className="mt-8 text-center">
        <TxSuccessModal 
        isOpen={!!successData}
        onClose={() => setSuccessData(null)}
        txHash={successData?.txHash || ''}
        title="Market Launched"
        subtitle={`Successfully deployed "${successData?.question.slice(0, 50)}${successData?.question && successData.question.length > 50 ? '...' : ''}" to the Shadow Network.`}
        primaryAction={successData?.slug ? {
          label: 'View Market',
          onClick: () => navigate(`/markets/${successData.slug}`)
        } : undefined}
      />
    </div>
    </div>
  );
}

export default CreateMarket;
