import { LayoutGrid, Zap, HelpCircle, Calendar, Shield, DollarSign } from 'lucide-react';
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import { useContract } from '../hooks/useContract';
import { marketsApi } from '../api/markets';

export function CreateMarket() {
  const navigate = useNavigate();
  const { createMarket, isInitializing } = useContract();
  const [formData, setFormData] = useState({
    question: '',
    description: '',
    category: 'General',
    resolutionDate: '',
    oracleAddress: 'mn_shield-addr_undeployed1pfytaphcp072fckzjqx5y2cd6yzy5jzz802gjev4w2vw97mjf0deny9jp0j527nrh2y326dr5x989fq4tdgldj5nula84d3s2y7pvmscsec3u', // Default to current user for testing
    initialLiquidity: '100',
  });
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);

    try {
      // Step 1: Create on-chain
      const txHash = await createMarket(
        '', // marketId auto-generated by contract
        formData.question,
        formData.oracleAddress,
        new Date(formData.resolutionDate)
      );

      if (txHash) {
        // Step 2: Sync to backend
        try {
          await marketsApi.create({
            question: formData.question,
            description: formData.description,
            category: formData.category,
            endTime: new Date(formData.resolutionDate).toISOString(),
            resolutionSource: 'Oracle',
            minBet: '1',
            maxBet: '1000',
            onchainId: '0', // Will be updated by indexer or backend
            txHash,
          });
          toast.success('Market synced to dashboard!');
        } catch (syncError) {
          console.error('Failed to sync market to backend:', syncError);
          toast.error('Market created on-chain but failed to sync to dashboard.');
        }
        
        navigate('/markets');
      }
    } catch (error) {
      console.error('Failed to create market:', error);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto py-12 px-6">
      <div className="mb-12 space-y-4">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-electric-blue/10 rounded-sm">
            <LayoutGrid className="w-5 h-5 text-electric-blue" />
          </div>
          <h1 className="text-4xl font-bold text-white tracking-tight">Create Market</h1>
        </div>
        <p className="text-slate-400 text-lg font-light leading-relaxed">
          Design and launch your own prediction market on the Shadow Network.
        </p>
      </div>

      <form onSubmit={handleSubmit} className="space-y-8 bg-slate-900/40 border border-white/5 p-8 rounded-sm backdrop-blur-sm">
        <div className="space-y-6">
          {/* Question Input */}
          <div className="space-y-2">
            <label className="text-[10px] font-mono text-slate-500 uppercase tracking-widest flex items-center gap-2">
              <HelpCircle className="w-3.5 h-3.5 text-electric-blue" />
              Market Question
            </label>
            <input
              required
              type="text"
              placeholder="e.g. Will Midnight mainnet launch in 2025?"
              value={formData.question}
              onChange={(e) => setFormData({ ...formData, question: e.target.value })}
              className="w-full bg-slate-950 border border-white/10 rounded-sm px-4 py-3 text-white placeholder:text-slate-700 focus:outline-none focus:border-electric-blue/50 transition-all font-light"
            />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Resolution Date */}
            <div className="space-y-2">
              <label className="text-[10px] font-mono text-slate-500 uppercase tracking-widest flex items-center gap-2">
                <Calendar className="w-3.5 h-3.5 text-electric-blue" />
                Resolution Date
              </label>
              <input
                required
                type="datetime-local"
                value={formData.resolutionDate}
                onChange={(e) => setFormData({ ...formData, resolutionDate: e.target.value })}
                className="w-full bg-slate-950 border border-white/10 rounded-sm px-4 py-3 text-white focus:outline-none focus:border-electric-blue/50 transition-all font-light"
              />
            </div>

            {/* Initial Liquidity */}
            <div className="space-y-2">
              <label className="text-[10px] font-mono text-slate-500 uppercase tracking-widest flex items-center gap-2">
                <DollarSign className="w-3.5 h-3.5 text-electric-blue" />
                Initial Liquidity (tDUST)
              </label>
              <input
                required
                type="number"
                value={formData.initialLiquidity}
                onChange={(e) => setFormData({ ...formData, initialLiquidity: e.target.value })}
                className="w-full bg-slate-950 border border-white/10 rounded-sm px-4 py-3 text-white focus:outline-none focus:border-electric-blue/50 transition-all font-light"
              />
            </div>
          </div>

          {/* Oracle Address */}
          <div className="space-y-2">
            <label className="text-[10px] font-mono text-slate-500 uppercase tracking-widest flex items-center gap-2">
              <Shield className="w-3.5 h-3.5 text-electric-blue" />
              Oracle / Resolver Address
            </label>
            <input
              required
              type="text"
              placeholder="mn_shield-addr_..."
              value={formData.oracleAddress}
              onChange={(e) => setFormData({ ...formData, oracleAddress: e.target.value })}
              className="w-full bg-slate-950 border border-white/10 rounded-sm px-4 py-3 text-white focus:outline-none focus:border-electric-blue/50 transition-all font-mono text-[11px]"
            />
          </div>
        </div>

        <div className="pt-6 border-t border-white/5">
          <button
            type="submit"
            disabled={isSubmitting || isInitializing}
            className="w-full py-4 bg-electric-blue text-white rounded-sm font-bold text-[11px] tracking-[0.2em] uppercase hover:brightness-110 disabled:opacity-50 transition-all flex items-center justify-center gap-3 shadow-[0_0_30px_rgba(59,130,246,0.3)]"
          >
            {isSubmitting ? (
              <div className="w-4 h-4 border-2 border-white/20 border-t-white rounded-full animate-spin" />
            ) : (
              <Zap className="w-4 h-4" />
            )}
            Launch Market on Shadow Network
          </button>
        </div>
      </form>

      <div className="mt-8 text-center">
        <span className="text-[10px] font-mono text-slate-700 uppercase tracking-[0.4em]">
          Stability Note: Market encryption is managed by the Midnight Protocol
        </span>
      </div>
    </div>
  );
}

export default CreateMarket;
