import { LayoutGrid, Zap, HelpCircle, Calendar, Shield, DollarSign, AlertCircle, Clock, ChevronLeft, ChevronRight, AlignLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useForm, Controller } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import toast from 'react-hot-toast';
import { format, addMonths, subMonths, startOfMonth, endOfMonth, eachDayOfInterval, isSameDay, isPast, isToday, startOfDay, addDays } from 'date-fns';
import { useState, useMemo } from 'react';
import { useContract } from '../hooks/useContract';
import { marketsApi } from '../api/markets';
import { CustomSelect } from '../components/common/CustomSelect';
import { TxSuccessModal } from '../components/common/TxSuccessModal';

const createMarketSchema = z.object({
  question: z.string().min(10, 'Question must be at least 10 characters').max(500),
  description: z.string().max(2000).optional(),
  category: z.string().min(1, 'Category is required'),
  resolutionDate: z.string().refine(val => new Date(val) > new Date(), {
    message: 'Resolution date must be in the future',
  }),
});

type CreateMarketFormData = z.infer<typeof createMarketSchema>;

export function CreateMarket() {
  const navigate = useNavigate();
  const { createMarket, isInitializing } = useContract();
  const [successData, setSuccessData] = useState<{ txHash: string; slug: string; question: string } | null>(null);
  
  const {
    register,
    handleSubmit,
    control,
    setValue,
    watch,
    formState: { errors, isSubmitting },
  } = useForm<CreateMarketFormData>({
    resolver: zodResolver(createMarketSchema),
    defaultValues: {
      category: 'Politics',
    },
});

  const onSubmit = async (data: CreateMarketFormData) => {
    console.log('DEBUG: CreateMarket.onSubmit called with form data:', data);
    try {
      // Step 1: Create on-chain
      console.log('DEBUG: Initiating on-chain market creation via hook...');
      const txHash = await createMarket(
        '', // marketId auto-generated by contract
        data.question,
        new Date(data.resolutionDate)
      );

      console.log('DEBUG: on-chain market creation attempt finished. txHash:', txHash);

      if (txHash) {
        // Step 2: Sync to backend (done in background or wait)
        console.log('DEBUG: Synchronizing new market to backend database...');
        try {
          const market = await marketsApi.create({
            question: data.question,
            description: data.description,
            category: data.category,
            endTime: new Date(data.resolutionDate).toISOString(),
            resolutionSource: 'Oracle',
            minBet: '1',
            maxBet: '1000',
            onchainId: '0', 
            txHash,
          });
          
          console.log('DEBUG: Backend synchronization successful. slug:', market.slug);
          
          // Show CUSTOM SUCCESS MODAL instead of redirecting
          setSuccessData({
            txHash,
            slug: market.slug || market.id,
            question: data.question
          });
          
        } catch (syncError) {
          console.error('DEBUG: Backend synchronization failed:', syncError);
          // If backend fails but on-chain succeeds, we still show the hash
          setSuccessData({
            txHash,
            slug: '', // Can't redirect to detail if sync failed
            question: data.question
          });
        }
      }
    } catch (error: any) {
      console.error('DEBUG: CreateMarket.onSubmit caught top-level error:', error);
      // Toast handled by contract service
    }
  };

  return (
    <div className="max-w-4xl mx-auto py-12 px-6">
      <div className="mb-12 space-y-4">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-electric-blue/10 rounded-sm">
            <LayoutGrid className="w-5 h-5 text-electric-blue" />
          </div>
          <h1 className="text-4xl font-bold text-white tracking-tight">Create Market</h1>
        </div>
        <p className="text-slate-400 text-lg font-light leading-relaxed">
          Design and launch your own prediction market on the Shadow Network.
        </p>
      </div>

      <form onSubmit={handleSubmit(onSubmit)} className="space-y-8 bg-slate-900/40 border border-white/5 p-8 rounded-sm backdrop-blur-sm">
        <div className="space-y-6">
          {/* Question Input */}
          <div className="space-y-2">
            <label className="text-[10px] font-mono text-slate-500 uppercase tracking-widest flex items-center justify-between">
              <span className="flex items-center gap-2">
                <HelpCircle className="w-3.5 h-3.5 text-electric-blue" />
                Market Question
              </span>
              {errors.question && (
                <span className="text-red-400 flex items-center gap-1">
                  <AlertCircle className="w-3 h-3" /> {errors.question.message}
                </span>
              )}
            </label>
            <input
              {...register('question')}
              type="text"
              placeholder="e.g. Will Midnight mainnet launch in 2025?"
              className={`w-full bg-slate-950 border rounded-sm px-4 py-3 text-white placeholder:text-slate-700 focus:outline-none transition-all font-light ${
                errors.question ? 'border-red-500/50' : 'border-white/10 focus:border-electric-blue/50'
              }`}
            />
          </div>
          
          {/* Description Input */}
          <div className="space-y-2">
            <label className="text-[10px] font-mono text-slate-500 uppercase tracking-widest flex items-center justify-between">
              <span className="flex items-center gap-2">
                <AlignLeft className="w-3.5 h-3.5 text-electric-blue" />
                Additional Details (Optional)
              </span>
            </label>
            <textarea
              {...register('description')}
              rows={3}
              placeholder="Provide context or resolution criteria..."
              className="w-full bg-slate-950 border border-white/10 rounded-sm px-4 py-3 text-white placeholder:text-slate-700 focus:outline-none focus:border-electric-blue/50 transition-all font-light resize-none text-sm"
            />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
             {/* Category Selection */}
             <CustomSelect
                label="Market Category"
                value={watch('category')}
                onChange={(val) => setValue('category', val)}
                error={errors.category?.message}
                options={[
                    { label: 'POLITICS', value: 'Politics', description: 'Elections, legislation, and global affairs' },
                    { label: 'CRYPTO', value: 'Crypto', description: 'Price action, protocol launches, and adoption' },
                    { label: 'SPORTS', value: 'Sports', description: 'Match results, player performance, and events' },
                    { label: 'SCIENCE', value: 'Science', description: 'Breakthroughs, space exploration, and tech' },
                    { label: 'OTHER', value: 'Other', description: 'Everything else in the shadow world' },
                ]}
             />
             <div className="hidden md:block" />
          </div>

          {/* Resolution Configuration */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {/* Custom Date/Time Selection */}
            <div className="space-y-4">
              <label className="text-[10px] font-mono text-slate-500 uppercase tracking-widest flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <Calendar className="w-3.5 h-3.5 text-electric-blue" />
                  Resolution Timeline
                </span>
                {errors.resolutionDate && (
                  <span className="text-red-400 flex items-center gap-1">
                    <AlertCircle className="w-3 h-3" /> Required Output
                  </span>
                )}
              </label>

              <Controller
                name="resolutionDate"
                control={control}
                render={({ field }) => {
                  const selectedDate = field.value ? new Date(field.value) : addDays(new Date(), 1);
                  const [currentMonth, setCurrentMonth] = useState(startOfMonth(selectedDate));
                  const [selectedTime, setSelectedTime] = useState(format(selectedDate, 'HH:mm'));

                  const days = useMemo(() => {
                    return eachDayOfInterval({
                      start: startOfMonth(currentMonth),
                      end: endOfMonth(currentMonth),
                    });
                  }, [currentMonth]);

                  const handleDateChange = (date: Date) => {
                    const [hours, minutes] = selectedTime.split(':').map(Number);
                    const newDate = new Date(date);
                    newDate.setHours(hours, minutes);
                    field.onChange(newDate.toISOString());
                  };

                  const handleTimeChange = (time: string) => {
                    setSelectedTime(time);
                    const [hours, minutes] = time.split(':').map(Number);
                    const newDate = new Date(selectedDate);
                    newDate.setHours(hours, minutes);
                    field.onChange(newDate.toISOString());
                  };

                  return (
                    <div className="flex flex-col md:flex-row gap-8 items-start">
                      {/* Calendar Section */}
                      <div className="flex-1 space-y-4 w-full">
                        {/* Calendar Header */}
                        <div className="flex items-center justify-between px-2">
                          <span className="text-xs font-bold text-white uppercase tracking-widest font-mono">
                            {format(currentMonth, 'MMMM yyyy')}
                          </span>
                          <div className="flex gap-1">
                            <button
                              type="button"
                              onClick={() => setCurrentMonth(subMonths(currentMonth, 1))}
                              className="p-1.5 hover:bg-white/5 rounded-sm transition-colors"
                            >
                              <ChevronLeft className="w-4 h-4 text-slate-500" />
                            </button>
                            <button
                              type="button"
                              onClick={() => setCurrentMonth(addMonths(currentMonth, 1))}
                              className="p-1.5 hover:bg-white/5 rounded-sm transition-colors"
                            >
                              <ChevronRight className="w-4 h-4 text-slate-500" />
                            </button>
                          </div>
                        </div>

                        {/* Day Grid */}
                        <div className="grid grid-cols-7 gap-1">
                          {['S', 'M', 'T', 'W', 'T', 'F', 'S'].map((day, index) => (
                            <div key={`${day}-${index}`} className="text-[8px] font-mono text-slate-700 text-center py-1 uppercase font-bold">
                              {day}
                            </div>
                          ))}
                          {days.map(day => {
                            const isSelected = isSameDay(day, selectedDate);
                            const isDisabled = isPast(day) && !isToday(day);
                            return (
                              <button
                                key={day.toISOString()}
                                type="button"
                                disabled={isDisabled}
                                onClick={() => handleDateChange(day)}
                                className={`aspect-square flex items-center justify-center text-[10px] rounded-sm transition-all font-mono ${
                                  isSelected
                                    ? 'bg-electric-blue text-white font-bold shadow-[0_0_15px_rgba(59,130,246,0.2)]'
                                    : isDisabled
                                    ? 'text-slate-800 opacity-20 cursor-not-allowed'
                                    : 'text-slate-400 hover:bg-white/5 hover:text-white'
                                }`}
                              >
                                {format(day, 'd')}
                              </button>
                            );
                          })}
                        </div>
                      </div>

                      {/* Divider */}
                      <div className="hidden md:block w-px h-48 bg-white/5 self-center" />

                      {/* Time Selection Section */}
                      <div className="w-full md:w-32 space-y-4">
                        <div className="flex items-center gap-2 text-slate-500">
                          <Clock className="w-3.5 h-3.5" />
                          <span className="text-[10px] font-mono uppercase tracking-widest">Time</span>
                        </div>
                        <div className="space-y-4">
                          <input
                            type="time"
                            value={selectedTime}
                            onChange={(e) => handleTimeChange(e.target.value)}
                            className="w-full bg-slate-950 border border-white/10 rounded-sm px-3 py-2 text-sm text-white font-mono focus:outline-none focus:border-electric-blue/50 transition-all"
                          />
                          <p className="text-[9px] text-slate-600 font-mono leading-tight uppercase">
                            Set resolution time in UTC
                          </p>
                        </div>
                      </div>
                    </div>
                  );
                }}
              />
            </div>

            <div className="space-y-8">
            <div className="space-y-4">
              {/* Optional: Add other settings here if needed */}
            </div>
            </div>
          </div>
        </div>

        <div className="pt-6 border-t border-white/5">
          <button
            type="submit"
            disabled={isSubmitting || isInitializing}
            className="w-full py-4 bg-electric-blue text-white rounded-sm font-bold text-[11px] tracking-[0.2em] uppercase hover:brightness-110 disabled:opacity-50 transition-all flex items-center justify-center gap-3 shadow-[0_0_30px_rgba(59,130,246,0.3)]"
          >
            {isSubmitting ? (
              <div className="w-4 h-4 border-2 border-white/20 border-t-white rounded-full animate-spin" />
            ) : (
              <Zap className="w-4 h-4" />
            )}
            Launch Market on Shadow Network
          </button>
        </div>
      </form>

      <div className="mt-8 text-center">
        <span className="text-[10px] font-mono text-slate-700 uppercase tracking-[0.4em]">
          Stability Note: Market encryption is managed by the Midnight Protocol
        </span>
        <TxSuccessModal 
        isOpen={!!successData}
        onClose={() => setSuccessData(null)}
        txHash={successData?.txHash || ''}
        title="Market Launched"
        subtitle={`Successfully deployed "${successData?.question.slice(0, 50)}${successData?.question && successData.question.length > 50 ? '...' : ''}" to the Shadow Network.`}
        primaryAction={successData?.slug ? {
          label: 'View Market',
          onClick: () => navigate(`/markets/${successData.slug}`)
        } : undefined}
      />
    </div>
    </div>
  );
}

export default CreateMarket;
