import bcrypt from 'bcryptjs';
import { eq } from 'drizzle-orm';
import { config } from '../config.js';
import { db } from '../db/client.js';
import { users } from '../db/schema.js';
import { generateId } from '../utils/crypto.js';
import logger from '../utils/logger.js';

/**
 * Initialize admin user from environment variables
 * Creates admin user if it doesn't exist
 */
export async function initializeAdmin() {
  logger.info('Initializing admin user...');

  try {
    const { adminUsername, adminPassword, adminAddress } = config;

    if (!adminUsername || !adminPassword) {
      logger.warn('Admin credentials not configured, skipping admin setup');
      return;
    }

    // Check if admin exists by username
    const existingAdmin = await db.query.users.findFirst({
      where: eq(users.username, adminUsername),
    });

    if (existingAdmin) {
      logger.info('Admin user already exists', {
        username: adminUsername,
        userId: existingAdmin.id,
      });

      // Ensure user has admin privileges
      if (!existingAdmin.isAdmin) {
        await db.update(users).set({ isAdmin: true }).where(eq(users.id, existingAdmin.id));
        logger.info('Updated user to admin role', { username: adminUsername });
      }

      // Sync admin address if it differs from config (e.g. from shielded to unshielded)
      if (adminAddress && existingAdmin.address !== adminAddress) {
        // Check if another user already has this address
        const userWithAddress = await db.query.users.findFirst({
          where: eq(users.address, adminAddress),
        });

        if (userWithAddress && userWithAddress.id !== existingAdmin.id) {
          if (!userWithAddress.username) {
            logger.info('Deleting anonymous user record with admin address', {
              userId: userWithAddress.id,
              address: adminAddress,
            });
            await db.delete(users).where(eq(users.id, userWithAddress.id));
          } else {
            logger.warn('Admin address conflict: address is already in use by another user with username', {
              adminUsername,
              conflictingUsername: userWithAddress.username,
              address: adminAddress,
            });
            return existingAdmin; // Stop here to avoid unique constraint violation
          }
        }

        await db
          .update(users)
          .set({ address: adminAddress, updatedAt: new Date() })
          .where(eq(users.id, existingAdmin.id));
        logger.info('Synchronized admin wallet address in database', {
          username: adminUsername,
          oldAddress: existingAdmin.address,
          newAddress: adminAddress,
        });
      }

      return existingAdmin;
    }

    // Create new admin user
    const hashedPassword = await bcrypt.hash(adminPassword, 10);

    // Check if another user already has the admin address
    let addressToUse = adminAddress;
    if (adminAddress) {
      const userWithAddress = await db.query.users.findFirst({
        where: eq(users.address, adminAddress),
      });

      if (userWithAddress) {
        // If they don't have a username, or have an auto-generated one (sm/...), promote them
        const isAutoGenerated = !userWithAddress.username || userWithAddress.username.startsWith('sm/');
        
        if (isAutoGenerated) {
          logger.info('Promoting existing user with admin address to admin role', {
            username: adminUsername,
            originalUsername: userWithAddress.username || 'anonymous',
            userId: userWithAddress.id,
          });

          const [updatedUser] = await db
            .update(users)
            .set({
              username: adminUsername,
              encryptedSeed: hashedPassword,
              isAdmin: true,
              reputation: 1000,
              updatedAt: new Date(),
            })
            .where(eq(users.id, userWithAddress.id))
            .returning();

          return updatedUser;
        } else {
          logger.warn('Admin address conflict: address is already in use by another user. Creating admin with unique temporary address.', {
            adminUsername,
            conflictingUsername: userWithAddress.username,
          });
          addressToUse = `admin_conflict_${Date.now()}`;
        }
      }
    }

    const [adminUser] = await db
      .insert(users)
      .values({
        id: generateId(),
        address: addressToUse || `admin_${Date.now()}`,
        username: adminUsername,
        encryptedSeed: hashedPassword, // Store password hash in encryptedSeed field
        isAdmin: true,
        reputation: 1000,
      })
      .returning();

    logger.info('Admin user created successfully', {
      username: adminUsername,
      userId: adminUser.id,
      defaultPassword: adminPassword === 'changeme',
    });

    if (adminPassword === 'changeme') {
      logger.warn('SECURITY WARNING: Admin using default password - CHANGE IMMEDIATELY!');
    }

    return adminUser;
  } catch (error) {
    logger.error('Failed to initialize admin user', { error });
    throw error;
  }
}

/**
 * Verify admin password for login
 */
export async function verifyAdminPassword(username: string, password: string): Promise<boolean> {
  try {
    const user = await db.query.users.findFirst({
      where: eq(users.username, username),
    });

    if (!user || !user.isAdmin || !user.encryptedSeed) {
      return false;
    }

    return await bcrypt.compare(password, user.encryptedSeed);
  } catch (error) {
    logger.error('Error verifying admin password', { error, username });
    return false;
  }
}
